# Generated by Django 5.1.4 on 2025-02-22 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nume promoție')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data creării')),
                ('date_expiry', models.DateTimeField(verbose_name='Data expirării')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Procent reducere')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descriere')),
                ('categories', models.ManyToManyField(related_name='promotii', to='aplicatie.category', verbose_name='Categorii')),
            ],
            options={
                'verbose_name': 'Promoție',
                'verbose_name_plural': 'Promoții',
            },
        ),
        migrations.CreateModel(
            name='Vizualizari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField(auto_now_add=True, verbose_name='Data vizualizării')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.book', verbose_name='Produs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Vizualizare',
                'verbose_name_plural': 'Vizualizări',
                'ordering': ['-date_viewed'],
            },
        ),
    ]
